### ISSUE TITLE
The map at the record View can't move.

### ISSUE THREAD

**Issue by Alex-ZHOU** [Alex-ZHOU/VMAndroid#1]
See the context in title.

**Comment by TomeOkin** [comment]
You can wrap it by [`NestedScrollView`](https://developer.android.com/reference/android/support/v4/widget/NestedScrollView.html)

**Comment by Alex-ZHOU** [comment]
@TomeOkin Could you speak Chinese,I feel hard to read you contribution.555~

**Comment by Alex-ZHOU** [comment]
@TomeOkin Thx your contribution.
